name: Build

on:
  push:
    tags: 
      - v*

defaults:
  run:
    shell: bash

jobs:
  Release:
    name: Release
    runs-on: windows-10
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Release Notes
        id: notes
        run: |
          RELEASE=$(cat RELEASE.md)
          RELEASE="${RELEASE//'%'/'%25'}"
          RELEASE="${RELEASE//$'\n'/'%0A'}"
          RELEASE="${RELEASE//$'\r'/'%0D'}"
          echo "::set-output name=notes::$RELEASE"

      - uses: actions/checkout@v2
      - run: make build
      - run: echo $TAG > dist/scroller/VERSION

      - name: Create Release
        uses: actions/create-release@master
        id: release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: $TAG
          release_name: $TAG
          body: |
            ${{ steps.notes.outputs.notes }}
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ./scroller-$TAG.zip
          asset_name: scroller-$TAG.zip
          asset_content_type: application/octet-stream