name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        default: v0.1.0

defaults:
  run:
    shell: bash

env:
  version: 

jobs:
  Release:
    name: Release
    runs-on: windows-10
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Release Notes
        id: notes
        run: |
          sed -i 's/<version>/${{ github.event.inputs.version }}/g' RELEASE.md
          RELEASE=$(cat RELEASE.md)
          RELEASE="${RELEASE//'%'/'%25'}"
          RELEASE="${RELEASE//$'\n'/'%0A'}"
          RELEASE="${RELEASE//$'\r'/'%0D'}"
          echo "::set-output name=notes::$RELEASE"

      - uses: actions/checkout@v2
      - run: make build
      - run: echo ${{ github.event.inputs.version }} > dist/scroller/VERSION
      - run: 7z a -tzip scroller-${{ github.event.inputs.version }}.zip dist/scroller

      - name: Create Release
        uses: actions/create-release@master
        id: release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: ${{ github.event.inputs.version }}
          body: |
            ${{ steps.notes.outputs.notes }}
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ./scroller-${{ github.event.inputs.version }}.zip
          asset_name: scroller-${{ github.event.inputs.version }}.zip
          asset_content_type: application/octet-stream
