name: Test (CI)

on:
  push:
    paths:
      - 'pyproject.toml'
      - 'poetry.lock'
      - 'Makefile'
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/test.yml'

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: windows-10
    steps:
      - uses: actions/checkout@v3
      - run: make install
      - run: make test
      - run: make build